# Generated by Django 3.2.8 on 2021-10-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='picture',
        ),
    ]
