# Generated by Django 3.2.8 on 2021-10-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_image_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
