# Generated by Django 3.2.8 on 2021-10-20 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_picture_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('male', models.BooleanField(default=False, verbose_name='MALE')),
                ('female', models.BooleanField(default=False, verbose_name='FEMALE')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
