# Generated by Django 3.2.8 on 2021-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=False),
        ),
    ]
