# Generated by Django 3.2.8 on 2021-10-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211020_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='enter your message here'),
        ),
    ]
